stages:
  - build
  - test
  - package
  - backup
  - deploy
  - restart
  - health_check
  - rollback

build:
  stage: build
  tags:
    - windows

  script:
    - '& "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" EmployeeManagementSystem.slnx /t:Restore'
    - '& "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" EmployeeManagementSystem.slnx /p:Configuration=Release'

  artifacts:
    paths:
      - EmployeeManagementSystem.Tests/bin/Release/net48/
    expire_in: 1 day

test:
  stage: test
  tags:
    - windows

  dependencies:
    - build

  script:
    - Get-ChildItem EmployeeManagementSystem.Tests\bin\Release\net48

    - '& "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" EmployeeManagementSystem.Tests\bin\Release\net48\EmployeeManagementSystem.Tests.dll'

package:
  stage: package
  tags:
    - windows

  dependencies:
    - build

  script:
    - |
      $version = $env:CI_PIPELINE_ID
      $publishPath = "$CI_PROJECT_DIR\publish\$version"

      if (Test-Path $publishPath) {
        Remove-Item $publishPath -Recurse -Force
      }

      & "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" `
       EmployeeManagementSystem\EmployeeManagementSystem.csproj `
       /t:WebPublish `
       /p:Configuration=Release `
       /p:WebPublishMethod=FileSystem `
       /p:PublishUrl="$publishPath" `
       /p:DeleteExistingFiles=True

      Write-Host ""
      Write-Host "Published files:"
      Get-ChildItem $publishPath

      $releasePath = "C:\Deployments\Releases\$version"

      if (Test-Path $releasePath) {
      Remove-Item $releasePath -Recurse -Force
      }

      New-Item -ItemType Directory -Path $releasePath | Out-Null
      Copy-Item "$publishPath\*" $releasePath -Recurse -Force

      Write-Host "Release stored at: $releasePath"
      $zipFile = "$CI_PROJECT_DIR\publish\EmployeeManagement_$version.zip"

      if (Test-Path $zipFile) {
      Remove-Item $zipFile -Force
      }

      Compress-Archive -Path "$publishPath\*" -DestinationPath $zipFile

      Write-Host "ZIP Package Created: $zipFile"

  artifacts:
    paths:
      - publish/
    expire_in: 1 day

backup:
  stage: backup
  tags:
    - windows

  script:
  - |
      $currentVersion = "0"

      if (Test-Path "C:\Deployments\Current\version.txt") {
      $currentVersion = Get-Content "C:\Deployments\Current\version.txt"
      }

      $backupPath = "C:\Deployments\Backups\$currentVersion"

      if ((Test-Path "C:\Deployments\Current") -and ((Get-ChildItem "C:\Deployments\Current").Count -gt 0)) {

          Write-Host "Creating backup for version $version..."

          if (Test-Path $backupPath) {
              Remove-Item $backupPath -Recurse -Force
          }

          New-Item -ItemType Directory -Path $backupPath | Out-Null

          Copy-Item "C:\Deployments\Current\*" $backupPath -Recurse -Force

          Write-Host "Backup stored at: $backupPath"
      }
      else {
          Write-Host "No previous deployment found. Skipping backup."
      }

deploy:
  stage: deploy
  tags:
    - windows

  dependencies:
    - package

  script:
    - |
      $version = $env:CI_PIPELINE_ID
      $artifactPath = "C:\Deployments\Releases\$version"
      $deployPath = "C:\Deployments\Current"

      Write-Host "Cleaning deployment directory..."

      if (Test-Path $deployPath) {
          Remove-Item "$deployPath\*" -Recurse -Force
      }
      else {
          New-Item -ItemType Directory -Path $deployPath | Out-Null
      }

      Write-Host "Deploying published files..."

      Copy-Item "$artifactPath\*" $deployPath -Recurse -Force

      Write-Host ""
      Write-Host "Deployment completed."
      Write-Host ""

      Set-Content -Path "$deployPath\version.txt" -Value $version

      Write-Host "Current deployed version: $version"

      Get-ChildItem $deployPath

restart:
  stage: restart
  tags:
    - windows

  script:
    - |
      Import-Module WebAdministration

      Write-Host "Restarting Application Pool..."

      Restart-WebAppPool -Name "EmployeeManagementPool"

      Write-Host "Checking Application Pool status..."

      Get-WebAppPoolState -Name "EmployeeManagementPool"

health_check:
  stage: health_check
  tags:
    - windows

  script:
    - |
      Write-Host "Checking application health..."

      $response = Invoke-WebRequest -Uri "http://localhost:8080" -UseBasicParsing

      Write-Host ""
      Write-Host "Status Code:" $response.StatusCode

      if ($response.StatusCode -eq 200) {
          Write-Host "Application is healthy."
      }
      else {
          throw "Health check failed."
      }

rollback:
  stage: rollback
  tags:
    - windows

  when: on_failure

  script:
    - |
      Write-Host "Starting automatic rollback..."
      powershell -ExecutionPolicy Bypass -File "$CI_PROJECT_DIR\DevOps\rollback.ps1"