stages:
  - build
  - test
  - package
  - backup

build:
  stage: build
  tags:
    - windows

  script:
    - '& "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" EmployeeManagementSystem.slnx /t:Restore'
    - '& "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" EmployeeManagementSystem.slnx /p:Configuration=Release'

  artifacts:
    paths:
      - EmployeeManagementSystem.Tests/bin/Release/net48/
    expire_in: 1 day

test:
  stage: test
  tags:
    - windows

  dependencies:
    - build

  script:
    - Get-ChildItem EmployeeManagementSystem.Tests\bin\Release\net48

    - '& "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" EmployeeManagementSystem.Tests\bin\Release\net48\EmployeeManagementSystem.Tests.dll'

package:
  stage: package
  tags:
    - windows

  dependencies:
    - build

  script:
  - '& "C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\amd64\MSBuild.exe" EmployeeManagementSystem\EmployeeManagementSystem.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl=publish'

  artifacts:
    paths:
      - EmployeeManagementSystem/publish/

backup:
  stage: backup
  tags:
    - windows

  script:
    - |
      if ((Test-Path "C:\Deployments\Current") -and ((Get-ChildItem "C:\Deployments\Current").Count -gt 0)) {
          Write-Host "Backing up current deployment..."
          Copy-Item "C:\Deployments\Current\*" "C:\Deployments\Backups\" -Recurse -Force
      }
      else {
          Write-Host "No previous deployment found. Skipping backup."
      }